
services:
  nginx:
    build:
      context: .
      dockerfile: docker-config/nginx/nginx.dockerfile
    volumes:
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/blog_inertia
    ports:
      - "8080:80"
    links:
      - php-fpm
      - mysql
      - node
    depends_on:
      - php-fpm
      - mysql
      - node

  php-fpm:
    build:
      context: .
      dockerfile: docker-config/php-fpm.dockerfile
    volumes:
      - ./:/var/www/blog_inertia
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    links:
      - node


  composer:
    image: composer
    volumes:
      - ./:/var/www/blog_inertia
    working_dir: /var/www/blog_inertia

  mysql:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=maestro
      - MYSQL_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8089:80
    environment:
       - PMA_HOST=mysql
    depends_on:
      - mysql

  node:
    image: node
    working_dir: /var/www/blog_inertia
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/blog_inertia
    tty: true
